export const allTerms = [
    { term: "Black Hole", def: "No light escapes" },
    { term: "Nebula", def: "Gas and dust cloud" },
    { term: "Comet", def: "Icy body, long tail" },
    { term: "Exoplanet", def: "Planet outside solar system" },
    { term: "Asteroid", def: "Rock orbiting sun" },
    { term: "Supernova", def: "Exploding star" },
    { term: "Pulsar", def: "Rotating neutron star" },
    { term: "Quasar", def: "Bright, active galactic core" },
    { term: "Galaxy", def: "Massive star system" },
    { term: "Red Giant", def: "Aging, large star" },
    { term: "White Dwarf", def: "Cooling star remnant" },
    { term: "Event Horizon", def: "Edge of a black hole" },
    { term: "Dark Matter", def: "Invisible mass in space" },
    { term: "Light-Year", def: "Distance light travels in a year" },
    { term: "Meteor", def: "Burning rock in atmosphere" },
    { term: "Meteorite", def: "Meteor hitting Earth" },
    { term: "Solar Flare", def: "Burst from the sun" },
    { term: "Orbit", def: "Path around a body" },
    { term: "Gravity", def: "Force pulling objects together" },
    { term: "Cosmic Microwave", def: "Big Bang radiation" },
    { term: "Oort Cloud", def: "Comet reservoir" },
    { term: "Kuiper Belt", def: "Beyond Neptune, icy bodies" },
    { term: "Hubble's Law", def: "Universe is expanding" },
    { term: "Redshift", def: "Light stretching, moving away" },
    { term: "Blue Shift", def: "Light compressing, moving closer" },
    { term: "Dark Energy", def: "Accelerating universe expansion" },
    { term: "Neutron Star", def: "Dense star core remnant" },
    { term: "Telescope", def: "Tool for distant viewing" },
    { term: "Spectroscopy", def: "Analyzing light spectrum" },
    { term: "Astrobiology", def: "Life in the universe study" },
    { term: "Cosmology", def: "Universe's origin and evolution" },
    { term: "Gravity Waves", def: "Ripples in spacetime" },
    { term: "Solar Eclipse", def: "Moon blocks sunlight" },
    { term: "Red Dwarf", def: "Small, cool star" },
    { term: "Blue Supergiant", def: "Massive, hot star" },
    { term: "Gamma Ray Burst", def: "Intense cosmic explosion" },
    { term: "Planetary Nebula", def: "Star shedding outer layers" },
    { term: "Solar System", def: "Sun and orbiting bodies" },
    { term: "Milky Way", def: "Our galaxy" },
    { term: "Andromeda", def: "Nearest spiral galaxy" },
    { term: "Big Bang", def: "Universe's origin event" },
    { term: "Cosmic Background Radiation", def: "Afterglow of Big Bang" },
    { term: "Asteroid Belt", def: "Between Mars and Jupiter" },
    { term: "Apollo Program", def: "Moon landing missions" },
    { term: "International Space Station", def: "Orbiting research lab" },
    { term: "James Webb Space Telescope", def: "Infrared space telescope" },
    { term: "Mercury", def: "Closest planet to the Sun" },
    { term: "Venus", def: "Hottest planet" },
    { term: "Earth", def: "Planet with life" },
    { term: "Mars", def: "The Red Planet" },
    { term: "Jupiter", def: "Largest planet" },
    { term: "Saturn", def: "Planet with rings" },
    { term: "Uranus", def: "Tilted ice giant" },
    { term: "Neptune", def: "Farthest planet" },
    { term: "Pluto", def: "Dwarf planet" },
    { term: "Europa", def: "Icy moon of Jupiter" },
    { term: "Titan", def: "Saturn's largest moon" },
    { term: "Ganymede", def: "Largest moon in the solar system" },
    { term: "Io", def: "Volcanic moon of Jupiter" },
    { term: "Ceres", def: "Dwarf planet in asteroid belt" },
    { term: "Kepler-22b", def: "Habitable exoplanet" },
    { term: "Proxima Centauri b", def: "Closest exoplanet" },
    { term: "TRAPPIST-1e", def: "Earth-like exoplanet" },
    { term: "Haumea", def: "Fast-spinning dwarf planet" },
    { term: "Makemake", def: "Kuiper Belt dwarf planet" },
    { term: "Eris", def: "Massive dwarf planet" },
    { term: "Solar Wind", def: "Charged particles from Sun" },
    { term: "Heliosphere", def: "Sun’s magnetic bubble" },
    { term: "Lagrange Point", def: "Gravity balance location" },
    { term: "Main Sequence", def: "Stable star phase" },
    { term: "Barycenter", def: "System's center of mass" },
    { term: "Chandrasekhar Limit", def: "White dwarf mass limit" },
    { term: "Coronal Mass Ejection", def: "Huge solar plasma burst" },
    { term: "Magnetosphere", def: "Magnetic field region" },
    { term: "Interstellar Medium", def: "Gas and dust between stars" },
    { term: "Accretion Disk", def: "Matter spiraling into object" },
    { term: "Elliptical Galaxy", def: "Rounded galaxy shape" },
    { term: "Spiral Galaxy", def: "Pinwheel-shaped galaxy" },
    { term: "Barred Spiral", def: "Spiral galaxy with bar" },
    { term: "Open Cluster", def: "Loose group of stars" },
    { term: "Globular Cluster", def: "Dense, spherical star group" },
    { term: "Roche Limit", def: "Tidal breakup distance" },
    { term: "Parallax", def: "Distance by star shift" },
    { term: "Spectral Type", def: "Star classification by color" },
    { term: "Photosphere", def: "Sun’s visible surface" },
    { term: "Corona", def: "Outer solar atmosphere" },
    { term: "Radiative Zone", def: "Energy moves by radiation" },
    { term: "Convective Zone", def: "Energy moves by convection" },
    { term: "Astrometry", def: "Measuring star positions" },
    { term: "Light Curve", def: "Graph of brightness change" },
    { term: "Transit Method", def: "Detects exoplanets by dip" },
    { term: "Radial Velocity", def: "Motion via Doppler shift" },
    { term: "Proper Motion", def: "Star's movement across sky" },
    { term: "Bolometric Magnitude", def: "Total emitted energy" },
    { term: "Absolute Magnitude", def: "Intrinsic brightness" },
    { term: "Apparent Magnitude", def: "Observed brightness" },
    { term: "Cepheid Variable", def: "Pulsating brightness star" },
    { term: "Type Ia Supernova", def: "Standard candle explosion" },
    { term: "Tidal Forces", def: "Gravity stretch effect" },
    { term: "Planetary Transit", def: "Planet crosses star face" },
    { term: "Intergalactic Space", def: "Between galaxies" },
    { term: "Galactic Halo", def: "Stars around galaxy" },
    { term: "Obliquity", def: "Planet's axial tilt" },
    { term: "Perihelion", def: "Closest to Sun point" },
    { term: "Aphelion", def: "Farthest from Sun point" },
    { term: "Inclination", def: "Orbit angle from plane" },
];